language: ruby
os:
- linux
- osx
rvm:
- 2.5
before_install:
- nvm install 8
- npm install -g puppeteer
- gem install metanorma-cli metanorma-mpfd
script:
- |
  source doctypes.env
  for template in $DOCTYPES
  do
    metanorma new test/$template --type $TYPE --doctype $template --template .
    metanorma compile $(ls -1 test/${template}/*.adoc  | head -1)
  done
